title: Gabriel Chen
email: gabrielchen@duck.com
description: > 
    Shut Down The Heart, And Open Your Eyes.
permalink: ':title/'
baseurl: "" 
url: "" 

# Author settings
author: Gabriel Chen 

# Contact links
email: gabrielchen@duck.com
website: gabrielchen.com
mastodon: gabriel

# Newsletter
mailchimp: 

# Paginate
paginate: 6
paginate_path: /page:num/

# collections
collections:
  books:
    output: true
    permalink: /books/:title/
  booktags:
    output: true
    permalink: /booktags/:title/
  movies:
    output: true
    permalink: /movies/:title/
  movietags:
    output: true
    permalink: /movietags/:title/
  images:
    output: true
    permalink: /images/:title/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
